name: TFJS
channels:
- !!python/unicode
  'defaults'
dependencies:
- python=2.7
- h5py==2.8.0
- pip==9.0.1
- numpy
- jupyter==1.0
- matplotlib
- scikit-learn==0.19.1
- scipy
- pandas==0.23.1
- pillow==4.0.0
- seaborn==0.7.1
- pip:
  - tensorflow==1.9.0
  - tensorflowjs==0.5.7
  - keras==2.1.5
  - coremltools==0.8
  - nltk==3.2.5
